/*=====================================================

	PackedTextures.h

	This file was generated by TexturePacker.

=====================================================*/

bool GetPackedTexture(const char *szFileName, unsigned char *&pPixels, int &nWidth, int &nHeight);

